version: "3.7"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-sqs-sub
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=us-west-2
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./src/test/resources/localstack-init.sh:/etc/localstack/init/ready.d/init-aws.sh
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

volumes:
  localstack-data:
    driver: local

networks:
  default:
    driver: bridge
